### ISSUE TITLE
Issue with gpsinit

### ISSUE THREAD

**Issue by jasonsinclair5** [f5eng/mt3339-utils#9]
Trying to run: gpsinit -s 115200 -f /etc/gpsinit_nav.conf /dev/ttyAMA0 , but I get this error below. Is there something I may be missing? 

pi@ntp1:/etc $  gpsinit -s 115200 -f /etc/gpsinit_nav.conf /dev/ttyAMA0
Traceback (most recent call last):
  File "/usr/local/bin/gpsinit", line 343, in <module>
    sys.exit(main() or 0)
  File "/usr/local/bin/gpsinit", line 310, in main
    fg = get_known_state(args.output_device, args.speed, None, False)
  File "/usr/local/bin/gpsinit", line 244, in get_known_state
    resp = send_and_wait(fg, "PMTK000", 0.5, retries=1)
  File "/usr/local/bin/gpsinit", line 108, in send_and_wait
    if thread.isAlive():
AttributeError: 'rx_loop_thread' object has no attribute 'isAlive'

**Comment by gtjoseph** [comment]
I'll try and get the fix tested and merged over this weekend.
